print("My name is Lorna")
print(" I am 18 years old")
print("I come from Kiambu county")
print("I love drawing, walking, playing the piano and disturbing cats")
print("---------------")
print("***************")
print("###############")